### ISSUE TITLE
How to reduce run time per image? 

### ISSUE THREAD

**Issue by darsw** [Utkarsh-Deshmukh/Single-Image-Dehazing-Python#3]
This is awesome work, do you know how to reduce runtime for image? Right now it takes about 3-4 seconds for 1280p

**Comment by Utkarsh-Deshmukh** [comment]
Here are a few ways to reduce the compute time:
1) resize the image to a lower resolution
2) reduce the `beta_max` parameter in the `CalTransmission.py` file
3) increase the parameter `beta_rate` in the `CalTransmission.py` file

Hope this helps.
