### ISSUE TITLE
Real time

### ISSUE THREAD

**Issue by vanDerAlgiers** [Utkarsh-Deshmukh/Single-Image-Dehazing-Python#4]
Can This algorithm works with a real time video?

**Comment by Utkarsh-Deshmukh** [comment]
In order to make it work for videos in realtime, we might need to do some optimizations. The simplest ones being downsampling the video frames, but that might reduce the resolution.

**Comment by vanDerAlgiers** [comment]
Thank you for replying. What about a C++ implementation can that make a difference?

**Comment by Utkarsh-Deshmukh** [comment]
Yes, migrating over to CPP would be another way to speed up things
