### ISSUE TITLE
Unexpected keyword argument 

### ISSUE THREAD

**Issue by Rad-Sroud333** [Utkarsh-Deshmukh/Single-Image-Dehazing-Python#6]
remove_haze() got an unexpected keyword argument showHazeTrasmissionMap

**Comment by Rad-Sroud333** [comment]
showHazeTrasmissionMap()

**Comment by Utkarsh-Deshmukh** [comment]
I think this is a typo. The variable name is `showTransmissionMap`

**Comment by Utkarsh-Deshmukh** [comment]
also please make sure about the version of the dehazing library. it should be 0.0.9
