### ISSUE TITLE
Not working with pip install

### ISSUE THREAD

**Issue by deeptft** [Utkarsh-Deshmukh/Single-Image-Dehazing-Python#8]
Hello brother shared code example is not working with pip install

The following error

File "/home/mrtan/ritvik/image_dehazer.py", line 15, in <module>
    HazeCorrectedImg, HazeMap = image_dehazer.remove_haze(HazeImg)		# Remove Haze
AttributeError: partially initialized module 'image_dehazer' has no attribute 'remove_haze' (most likely due to a circular import)

**Comment by Utkarsh-Deshmukh** [comment]
i am unable to reproduce this.
Can you give me some details about what procedures you are following?
Be as verbose as possible, as this will help debug this issue

**Comment by Utkarsh-Deshmukh** [comment]
another tip:
try installing this in a venv - you might already have some lib that may be causing the circular lib dependency.
Also, try uninstalling opencv before installing image_dehazer. image_dehazer internally is dependent on opencv, and would be trying to install it

**Comment by deeptft** [comment]
Hi, @Utkarsh-Deshmukh. The Issue gets resolved when I create a new environment. Thanks for your support.
